# Generated by Django 5.0.7 on 2024-07-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_attempt_client_mailing_message_delete_mymodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={"verbose_name": "Attempt", "verbose_name_plural": "Attempts"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Mailing", "verbose_name_plural": "Mailings"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
    ]
